# Generated by Django 3.1.2 on 2021-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('category', models.ManyToManyField(related_name='category', to='store.Category')),
                ('image', models.ManyToManyField(related_name='product_image', to='store.Image')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ManyToManyField(related_name='category_image', to='store.Image'),
        ),
    ]
