# Generated by Django 3.1.2 on 2021-04-18 19:57

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Image.where_to_upload),
        ),
    ]
